% RPG_PLAYER_CHARACTER.CLS - Version 0.1
% Raphaël Perret & Guillaume Godet-Bar

\NeedsTeXFormat{LaTeX2e}

\def \ClassName {rpg_player_character}
\def \fileversion {0.1}
\def \filedate {2011/01/16}
\def \fileinfo {player character description}

\ProvidesClass {rpg_player_character} [\filedate \space \fileversion \space \fileinfo ]

\LoadClass{article}

\RequirePackage{rpg_all_basic}

\pagestyle{headings}
